# Generated by Django 5.1.1 on 2024-10-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=12)),
                ("lname", models.CharField(max_length=12)),
                ("phone", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=30)),
                ("message", models.TextField(max_length=50)),
                ("date", models.DateField()),
            ],
        ),
    ]
