# Generated by Django 5.1.1 on 2024-10-06 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="fname",
            new_name="name",
        ),
    ]
